//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HotelWebService.ServiceDisponibilite {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HotelDisponibiliteSoap", Namespace="http://tempuri.org/")]
    public partial class HotelDisponibilite : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AfficherOffreDisponibleOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfficherOffreDisponibleAvecImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfficherOffreDisponibleGUIOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHotelOperationCompleted;
        
        private System.Threading.SendOrPostCallback faireReservationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HotelDisponibilite() {
            this.Url = global::HotelWebService.Properties.Settings.Default.HotelWebService_ServiceDisponibilite_HotelDisponibilite;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AfficherOffreDisponibleCompletedEventHandler AfficherOffreDisponibleCompleted;
        
        /// <remarks/>
        public event AfficherOffreDisponibleAvecImageCompletedEventHandler AfficherOffreDisponibleAvecImageCompleted;
        
        /// <remarks/>
        public event AfficherOffreDisponibleGUICompletedEventHandler AfficherOffreDisponibleGUICompleted;
        
        /// <remarks/>
        public event getHotelCompletedEventHandler getHotelCompleted;
        
        /// <remarks/>
        public event faireReservationCompletedEventHandler faireReservationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfficherOffreDisponible", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Offre[] AfficherOffreDisponible(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            object[] results = this.Invoke("AfficherOffreDisponible", new object[] {
                        login,
                        password,
                        dateArrive,
                        dateDepart,
                        nbPersonne});
            return ((Offre[])(results[0]));
        }
        
        /// <remarks/>
        public void AfficherOffreDisponibleAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            this.AfficherOffreDisponibleAsync(login, password, dateArrive, dateDepart, nbPersonne, null);
        }
        
        /// <remarks/>
        public void AfficherOffreDisponibleAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne, object userState) {
            if ((this.AfficherOffreDisponibleOperationCompleted == null)) {
                this.AfficherOffreDisponibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfficherOffreDisponibleOperationCompleted);
            }
            this.InvokeAsync("AfficherOffreDisponible", new object[] {
                        login,
                        password,
                        dateArrive,
                        dateDepart,
                        nbPersonne}, this.AfficherOffreDisponibleOperationCompleted, userState);
        }
        
        private void OnAfficherOffreDisponibleOperationCompleted(object arg) {
            if ((this.AfficherOffreDisponibleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfficherOffreDisponibleCompleted(this, new AfficherOffreDisponibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfficherOffreDisponibleAvecImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Offre[] AfficherOffreDisponibleAvecImage(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            object[] results = this.Invoke("AfficherOffreDisponibleAvecImage", new object[] {
                        login,
                        password,
                        dateArrive,
                        dateDepart,
                        nbPersonne});
            return ((Offre[])(results[0]));
        }
        
        /// <remarks/>
        public void AfficherOffreDisponibleAvecImageAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            this.AfficherOffreDisponibleAvecImageAsync(login, password, dateArrive, dateDepart, nbPersonne, null);
        }
        
        /// <remarks/>
        public void AfficherOffreDisponibleAvecImageAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne, object userState) {
            if ((this.AfficherOffreDisponibleAvecImageOperationCompleted == null)) {
                this.AfficherOffreDisponibleAvecImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfficherOffreDisponibleAvecImageOperationCompleted);
            }
            this.InvokeAsync("AfficherOffreDisponibleAvecImage", new object[] {
                        login,
                        password,
                        dateArrive,
                        dateDepart,
                        nbPersonne}, this.AfficherOffreDisponibleAvecImageOperationCompleted, userState);
        }
        
        private void OnAfficherOffreDisponibleAvecImageOperationCompleted(object arg) {
            if ((this.AfficherOffreDisponibleAvecImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfficherOffreDisponibleAvecImageCompleted(this, new AfficherOffreDisponibleAvecImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfficherOffreDisponibleGUI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Offre[] AfficherOffreDisponibleGUI(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            object[] results = this.Invoke("AfficherOffreDisponibleGUI", new object[] {
                        login,
                        password,
                        dateArrive,
                        dateDepart,
                        nbPersonne});
            return ((Offre[])(results[0]));
        }
        
        /// <remarks/>
        public void AfficherOffreDisponibleGUIAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            this.AfficherOffreDisponibleGUIAsync(login, password, dateArrive, dateDepart, nbPersonne, null);
        }
        
        /// <remarks/>
        public void AfficherOffreDisponibleGUIAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne, object userState) {
            if ((this.AfficherOffreDisponibleGUIOperationCompleted == null)) {
                this.AfficherOffreDisponibleGUIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfficherOffreDisponibleGUIOperationCompleted);
            }
            this.InvokeAsync("AfficherOffreDisponibleGUI", new object[] {
                        login,
                        password,
                        dateArrive,
                        dateDepart,
                        nbPersonne}, this.AfficherOffreDisponibleGUIOperationCompleted, userState);
        }
        
        private void OnAfficherOffreDisponibleGUIOperationCompleted(object arg) {
            if ((this.AfficherOffreDisponibleGUICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfficherOffreDisponibleGUICompleted(this, new AfficherOffreDisponibleGUICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getHotel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel getHotel() {
            object[] results = this.Invoke("getHotel", new object[0]);
            return ((Hotel)(results[0]));
        }
        
        /// <remarks/>
        public void getHotelAsync() {
            this.getHotelAsync(null);
        }
        
        /// <remarks/>
        public void getHotelAsync(object userState) {
            if ((this.getHotelOperationCompleted == null)) {
                this.getHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHotelOperationCompleted);
            }
            this.InvokeAsync("getHotel", new object[0], this.getHotelOperationCompleted, userState);
        }
        
        private void OngetHotelOperationCompleted(object arg) {
            if ((this.getHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHotelCompleted(this, new getHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/faireReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reservation faireReservation(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            object[] results = this.Invoke("faireReservation", new object[] {
                        login,
                        password,
                        idOffre,
                        nomPersonne,
                        prenom,
                        numeroCB,
                        nbPersonne});
            return ((Reservation)(results[0]));
        }
        
        /// <remarks/>
        public void faireReservationAsync(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            this.faireReservationAsync(login, password, idOffre, nomPersonne, prenom, numeroCB, nbPersonne, null);
        }
        
        /// <remarks/>
        public void faireReservationAsync(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne, object userState) {
            if ((this.faireReservationOperationCompleted == null)) {
                this.faireReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfaireReservationOperationCompleted);
            }
            this.InvokeAsync("faireReservation", new object[] {
                        login,
                        password,
                        idOffre,
                        nomPersonne,
                        prenom,
                        numeroCB,
                        nbPersonne}, this.faireReservationOperationCompleted, userState);
        }
        
        private void OnfaireReservationOperationCompleted(object arg) {
            if ((this.faireReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.faireReservationCompleted(this, new faireReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Offre {
        
        private string idOffreField;
        
        private TypeChambre numChambreField;
        
        private System.DateTime debField;
        
        private System.DateTime finField;
        
        private double prixTotalOffreField;
        
        /// <remarks/>
        public string idOffre {
            get {
                return this.idOffreField;
            }
            set {
                this.idOffreField = value;
            }
        }
        
        /// <remarks/>
        public TypeChambre numChambre {
            get {
                return this.numChambreField;
            }
            set {
                this.numChambreField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime deb {
            get {
                return this.debField;
            }
            set {
                this.debField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fin {
            get {
                return this.finField;
            }
            set {
                this.finField = value;
            }
        }
        
        /// <remarks/>
        public double prixTotalOffre {
            get {
                return this.prixTotalOffreField;
            }
            set {
                this.prixTotalOffreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TypeChambre {
        
        private int numChambreField;
        
        private int nbLitsField;
        
        private string imageURLField;
        
        private byte[] imageField;
        
        private Reservation[] listReservationsField;
        
        /// <remarks/>
        public int numChambre {
            get {
                return this.numChambreField;
            }
            set {
                this.numChambreField = value;
            }
        }
        
        /// <remarks/>
        public int nbLits {
            get {
                return this.nbLitsField;
            }
            set {
                this.nbLitsField = value;
            }
        }
        
        /// <remarks/>
        public string imageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public Reservation[] ListReservations {
            get {
                return this.listReservationsField;
            }
            set {
                this.listReservationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reservation {
        
        private string nomClientField;
        
        private string prenomClientField;
        
        private System.DateTime dateArriveeField;
        
        private System.DateTime dateDepartField;
        
        private int numCarteBancaireField;
        
        private int nbPersonneField;
        
        private int dureeSejourField;
        
        private double prixTotalField;
        
        /// <remarks/>
        public string nomClient {
            get {
                return this.nomClientField;
            }
            set {
                this.nomClientField = value;
            }
        }
        
        /// <remarks/>
        public string prenomClient {
            get {
                return this.prenomClientField;
            }
            set {
                this.prenomClientField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateArrivee {
            get {
                return this.dateArriveeField;
            }
            set {
                this.dateArriveeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateDepart {
            get {
                return this.dateDepartField;
            }
            set {
                this.dateDepartField = value;
            }
        }
        
        /// <remarks/>
        public int numCarteBancaire {
            get {
                return this.numCarteBancaireField;
            }
            set {
                this.numCarteBancaireField = value;
            }
        }
        
        /// <remarks/>
        public int nbPersonne {
            get {
                return this.nbPersonneField;
            }
            set {
                this.nbPersonneField = value;
            }
        }
        
        /// <remarks/>
        public int dureeSejour {
            get {
                return this.dureeSejourField;
            }
            set {
                this.dureeSejourField = value;
            }
        }
        
        /// <remarks/>
        public double prixTotal {
            get {
                return this.prixTotalField;
            }
            set {
                this.prixTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Hotel {
        
        private TypeChambre[] listChambresField;
        
        private string nomHotelField;
        
        private string adresseHotelField;
        
        private string villeField;
        
        private string paysHotelField;
        
        private int nbEtoilesField;
        
        private float prixNuitField;
        
        /// <remarks/>
        public TypeChambre[] ListChambres {
            get {
                return this.listChambresField;
            }
            set {
                this.listChambresField = value;
            }
        }
        
        /// <remarks/>
        public string nomHotel {
            get {
                return this.nomHotelField;
            }
            set {
                this.nomHotelField = value;
            }
        }
        
        /// <remarks/>
        public string adresseHotel {
            get {
                return this.adresseHotelField;
            }
            set {
                this.adresseHotelField = value;
            }
        }
        
        /// <remarks/>
        public string ville {
            get {
                return this.villeField;
            }
            set {
                this.villeField = value;
            }
        }
        
        /// <remarks/>
        public string paysHotel {
            get {
                return this.paysHotelField;
            }
            set {
                this.paysHotelField = value;
            }
        }
        
        /// <remarks/>
        public int nbEtoiles {
            get {
                return this.nbEtoilesField;
            }
            set {
                this.nbEtoilesField = value;
            }
        }
        
        /// <remarks/>
        public float prixNuit {
            get {
                return this.prixNuitField;
            }
            set {
                this.prixNuitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AfficherOffreDisponibleCompletedEventHandler(object sender, AfficherOffreDisponibleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfficherOffreDisponibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfficherOffreDisponibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Offre[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Offre[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AfficherOffreDisponibleAvecImageCompletedEventHandler(object sender, AfficherOffreDisponibleAvecImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfficherOffreDisponibleAvecImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfficherOffreDisponibleAvecImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Offre[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Offre[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AfficherOffreDisponibleGUICompletedEventHandler(object sender, AfficherOffreDisponibleGUICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfficherOffreDisponibleGUICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfficherOffreDisponibleGUICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Offre[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Offre[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getHotelCompletedEventHandler(object sender, getHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void faireReservationCompletedEventHandler(object sender, faireReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class faireReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal faireReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reservation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reservation)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591