//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebService.ServiceDisponibilite2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offre", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Offre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idOffreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelWebService.ServiceDisponibilite2.TypeChambre numChambreField;
        
        private System.DateTime debField;
        
        private System.DateTime finField;
        
        private double prixTotalOffreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idOffre {
            get {
                return this.idOffreField;
            }
            set {
                if ((object.ReferenceEquals(this.idOffreField, value) != true)) {
                    this.idOffreField = value;
                    this.RaisePropertyChanged("idOffre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HotelWebService.ServiceDisponibilite2.TypeChambre numChambre {
            get {
                return this.numChambreField;
            }
            set {
                if ((object.ReferenceEquals(this.numChambreField, value) != true)) {
                    this.numChambreField = value;
                    this.RaisePropertyChanged("numChambre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime deb {
            get {
                return this.debField;
            }
            set {
                if ((this.debField.Equals(value) != true)) {
                    this.debField = value;
                    this.RaisePropertyChanged("deb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime fin {
            get {
                return this.finField;
            }
            set {
                if ((this.finField.Equals(value) != true)) {
                    this.finField = value;
                    this.RaisePropertyChanged("fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double prixTotalOffre {
            get {
                return this.prixTotalOffreField;
            }
            set {
                if ((this.prixTotalOffreField.Equals(value) != true)) {
                    this.prixTotalOffreField = value;
                    this.RaisePropertyChanged("prixTotalOffre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeChambre", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TypeChambre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int numChambreField;
        
        private int nbLitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelWebService.ServiceDisponibilite2.Reservation[] ListReservationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numChambre {
            get {
                return this.numChambreField;
            }
            set {
                if ((this.numChambreField.Equals(value) != true)) {
                    this.numChambreField = value;
                    this.RaisePropertyChanged("numChambre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int nbLits {
            get {
                return this.nbLitsField;
            }
            set {
                if ((this.nbLitsField.Equals(value) != true)) {
                    this.nbLitsField = value;
                    this.RaisePropertyChanged("nbLits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string imageURL {
            get {
                return this.imageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.imageURLField, value) != true)) {
                    this.imageURLField = value;
                    this.RaisePropertyChanged("imageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public HotelWebService.ServiceDisponibilite2.Reservation[] ListReservations {
            get {
                return this.ListReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ListReservationsField, value) != true)) {
                    this.ListReservationsField = value;
                    this.RaisePropertyChanged("ListReservations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomClientField;
        
        private System.DateTime dateArriveeField;
        
        private System.DateTime dateDepartField;
        
        private int numCarteBancaireField;
        
        private int nbPersonneField;
        
        private int dureeSejourField;
        
        private double prixTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nomClient {
            get {
                return this.nomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.nomClientField, value) != true)) {
                    this.nomClientField = value;
                    this.RaisePropertyChanged("nomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string prenomClient {
            get {
                return this.prenomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomClientField, value) != true)) {
                    this.prenomClientField = value;
                    this.RaisePropertyChanged("prenomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime dateArrivee {
            get {
                return this.dateArriveeField;
            }
            set {
                if ((this.dateArriveeField.Equals(value) != true)) {
                    this.dateArriveeField = value;
                    this.RaisePropertyChanged("dateArrivee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime dateDepart {
            get {
                return this.dateDepartField;
            }
            set {
                if ((this.dateDepartField.Equals(value) != true)) {
                    this.dateDepartField = value;
                    this.RaisePropertyChanged("dateDepart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int numCarteBancaire {
            get {
                return this.numCarteBancaireField;
            }
            set {
                if ((this.numCarteBancaireField.Equals(value) != true)) {
                    this.numCarteBancaireField = value;
                    this.RaisePropertyChanged("numCarteBancaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int nbPersonne {
            get {
                return this.nbPersonneField;
            }
            set {
                if ((this.nbPersonneField.Equals(value) != true)) {
                    this.nbPersonneField = value;
                    this.RaisePropertyChanged("nbPersonne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int dureeSejour {
            get {
                return this.dureeSejourField;
            }
            set {
                if ((this.dureeSejourField.Equals(value) != true)) {
                    this.dureeSejourField = value;
                    this.RaisePropertyChanged("dureeSejour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double prixTotal {
            get {
                return this.prixTotalField;
            }
            set {
                if ((this.prixTotalField.Equals(value) != true)) {
                    this.prixTotalField = value;
                    this.RaisePropertyChanged("prixTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelWebService.ServiceDisponibilite2.TypeChambre[] ListChambresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomHotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresseHotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string villeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paysHotelField;
        
        private int nbEtoilesField;
        
        private float prixNuitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HotelWebService.ServiceDisponibilite2.TypeChambre[] ListChambres {
            get {
                return this.ListChambresField;
            }
            set {
                if ((object.ReferenceEquals(this.ListChambresField, value) != true)) {
                    this.ListChambresField = value;
                    this.RaisePropertyChanged("ListChambres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nomHotel {
            get {
                return this.nomHotelField;
            }
            set {
                if ((object.ReferenceEquals(this.nomHotelField, value) != true)) {
                    this.nomHotelField = value;
                    this.RaisePropertyChanged("nomHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string adresseHotel {
            get {
                return this.adresseHotelField;
            }
            set {
                if ((object.ReferenceEquals(this.adresseHotelField, value) != true)) {
                    this.adresseHotelField = value;
                    this.RaisePropertyChanged("adresseHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ville {
            get {
                return this.villeField;
            }
            set {
                if ((object.ReferenceEquals(this.villeField, value) != true)) {
                    this.villeField = value;
                    this.RaisePropertyChanged("ville");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string paysHotel {
            get {
                return this.paysHotelField;
            }
            set {
                if ((object.ReferenceEquals(this.paysHotelField, value) != true)) {
                    this.paysHotelField = value;
                    this.RaisePropertyChanged("paysHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int nbEtoiles {
            get {
                return this.nbEtoilesField;
            }
            set {
                if ((this.nbEtoilesField.Equals(value) != true)) {
                    this.nbEtoilesField = value;
                    this.RaisePropertyChanged("nbEtoiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public float prixNuit {
            get {
                return this.prixNuitField;
            }
            set {
                if ((this.prixNuitField.Equals(value) != true)) {
                    this.prixNuitField = value;
                    this.RaisePropertyChanged("prixNuit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDisponibilite2.HotelDisponibiliteSoap")]
    public interface HotelDisponibiliteSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfficherOffreDisponible", ReplyAction="*")]
        HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleResponse AfficherOffreDisponible(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfficherOffreDisponible", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleResponse> AfficherOffreDisponibleAsync(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfficherOffreDisponibleAvecImage", ReplyAction="*")]
        HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageResponse AfficherOffreDisponibleAvecImage(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfficherOffreDisponibleAvecImage", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageResponse> AfficherOffreDisponibleAvecImageAsync(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfficherOffreDisponibleGUI", ReplyAction="*")]
        HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIResponse AfficherOffreDisponibleGUI(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfficherOffreDisponibleGUI", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIResponse> AfficherOffreDisponibleGUIAsync(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequest request);
        
        // CODEGEN: Generating message contract since element name getHotelResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHotel", ReplyAction="*")]
        HotelWebService.ServiceDisponibilite2.getHotelResponse getHotel(HotelWebService.ServiceDisponibilite2.getHotelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.getHotelResponse> getHotelAsync(HotelWebService.ServiceDisponibilite2.getHotelRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faireReservation", ReplyAction="*")]
        HotelWebService.ServiceDisponibilite2.faireReservationResponse faireReservation(HotelWebService.ServiceDisponibilite2.faireReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faireReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.faireReservationResponse> faireReservationAsync(HotelWebService.ServiceDisponibilite2.faireReservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AfficherOffreDisponibleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AfficherOffreDisponible", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequestBody Body;
        
        public AfficherOffreDisponibleRequest() {
        }
        
        public AfficherOffreDisponibleRequest(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AfficherOffreDisponibleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dateArrive;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dateDepart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nbPersonne;
        
        public AfficherOffreDisponibleRequestBody() {
        }
        
        public AfficherOffreDisponibleRequestBody(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            this.login = login;
            this.password = password;
            this.dateArrive = dateArrive;
            this.dateDepart = dateDepart;
            this.nbPersonne = nbPersonne;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AfficherOffreDisponibleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AfficherOffreDisponibleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleResponseBody Body;
        
        public AfficherOffreDisponibleResponse() {
        }
        
        public AfficherOffreDisponibleResponse(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AfficherOffreDisponibleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponibleResult;
        
        public AfficherOffreDisponibleResponseBody() {
        }
        
        public AfficherOffreDisponibleResponseBody(HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponibleResult) {
            this.AfficherOffreDisponibleResult = AfficherOffreDisponibleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AfficherOffreDisponibleAvecImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AfficherOffreDisponibleAvecImage", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequestBody Body;
        
        public AfficherOffreDisponibleAvecImageRequest() {
        }
        
        public AfficherOffreDisponibleAvecImageRequest(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AfficherOffreDisponibleAvecImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dateArrive;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dateDepart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nbPersonne;
        
        public AfficherOffreDisponibleAvecImageRequestBody() {
        }
        
        public AfficherOffreDisponibleAvecImageRequestBody(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            this.login = login;
            this.password = password;
            this.dateArrive = dateArrive;
            this.dateDepart = dateDepart;
            this.nbPersonne = nbPersonne;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AfficherOffreDisponibleAvecImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AfficherOffreDisponibleAvecImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageResponseBody Body;
        
        public AfficherOffreDisponibleAvecImageResponse() {
        }
        
        public AfficherOffreDisponibleAvecImageResponse(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AfficherOffreDisponibleAvecImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponibleAvecImageResult;
        
        public AfficherOffreDisponibleAvecImageResponseBody() {
        }
        
        public AfficherOffreDisponibleAvecImageResponseBody(HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponibleAvecImageResult) {
            this.AfficherOffreDisponibleAvecImageResult = AfficherOffreDisponibleAvecImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AfficherOffreDisponibleGUIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AfficherOffreDisponibleGUI", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequestBody Body;
        
        public AfficherOffreDisponibleGUIRequest() {
        }
        
        public AfficherOffreDisponibleGUIRequest(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AfficherOffreDisponibleGUIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dateArrive;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dateDepart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nbPersonne;
        
        public AfficherOffreDisponibleGUIRequestBody() {
        }
        
        public AfficherOffreDisponibleGUIRequestBody(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            this.login = login;
            this.password = password;
            this.dateArrive = dateArrive;
            this.dateDepart = dateDepart;
            this.nbPersonne = nbPersonne;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AfficherOffreDisponibleGUIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AfficherOffreDisponibleGUIResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIResponseBody Body;
        
        public AfficherOffreDisponibleGUIResponse() {
        }
        
        public AfficherOffreDisponibleGUIResponse(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AfficherOffreDisponibleGUIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponibleGUIResult;
        
        public AfficherOffreDisponibleGUIResponseBody() {
        }
        
        public AfficherOffreDisponibleGUIResponseBody(HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponibleGUIResult) {
            this.AfficherOffreDisponibleGUIResult = AfficherOffreDisponibleGUIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHotelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHotel", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.getHotelRequestBody Body;
        
        public getHotelRequest() {
        }
        
        public getHotelRequest(HotelWebService.ServiceDisponibilite2.getHotelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getHotelRequestBody {
        
        public getHotelRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHotelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHotelResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.getHotelResponseBody Body;
        
        public getHotelResponse() {
        }
        
        public getHotelResponse(HotelWebService.ServiceDisponibilite2.getHotelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHotelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HotelWebService.ServiceDisponibilite2.Hotel getHotelResult;
        
        public getHotelResponseBody() {
        }
        
        public getHotelResponseBody(HotelWebService.ServiceDisponibilite2.Hotel getHotelResult) {
            this.getHotelResult = getHotelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class faireReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="faireReservation", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.faireReservationRequestBody Body;
        
        public faireReservationRequest() {
        }
        
        public faireReservationRequest(HotelWebService.ServiceDisponibilite2.faireReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class faireReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idOffre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nomPersonne;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string prenom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int numeroCB;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int nbPersonne;
        
        public faireReservationRequestBody() {
        }
        
        public faireReservationRequestBody(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            this.login = login;
            this.password = password;
            this.idOffre = idOffre;
            this.nomPersonne = nomPersonne;
            this.prenom = prenom;
            this.numeroCB = numeroCB;
            this.nbPersonne = nbPersonne;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class faireReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="faireReservationResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite2.faireReservationResponseBody Body;
        
        public faireReservationResponse() {
        }
        
        public faireReservationResponse(HotelWebService.ServiceDisponibilite2.faireReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class faireReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HotelWebService.ServiceDisponibilite2.Reservation faireReservationResult;
        
        public faireReservationResponseBody() {
        }
        
        public faireReservationResponseBody(HotelWebService.ServiceDisponibilite2.Reservation faireReservationResult) {
            this.faireReservationResult = faireReservationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelDisponibiliteSoapChannel : HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelDisponibiliteSoapClient : System.ServiceModel.ClientBase<HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap>, HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap {
        
        public HotelDisponibiliteSoapClient() {
        }
        
        public HotelDisponibiliteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelDisponibiliteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelDisponibiliteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelDisponibiliteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleResponse HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.AfficherOffreDisponible(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequest request) {
            return base.Channel.AfficherOffreDisponible(request);
        }
        
        public HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponible(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequest inValue = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.dateArrive = dateArrive;
            inValue.Body.dateDepart = dateDepart;
            inValue.Body.nbPersonne = nbPersonne;
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleResponse retVal = ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).AfficherOffreDisponible(inValue);
            return retVal.Body.AfficherOffreDisponibleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleResponse> HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.AfficherOffreDisponibleAsync(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequest request) {
            return base.Channel.AfficherOffreDisponibleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleResponse> AfficherOffreDisponibleAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequest inValue = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.dateArrive = dateArrive;
            inValue.Body.dateDepart = dateDepart;
            inValue.Body.nbPersonne = nbPersonne;
            return ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).AfficherOffreDisponibleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageResponse HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.AfficherOffreDisponibleAvecImage(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequest request) {
            return base.Channel.AfficherOffreDisponibleAvecImage(request);
        }
        
        public HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponibleAvecImage(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequest inValue = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.dateArrive = dateArrive;
            inValue.Body.dateDepart = dateDepart;
            inValue.Body.nbPersonne = nbPersonne;
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageResponse retVal = ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).AfficherOffreDisponibleAvecImage(inValue);
            return retVal.Body.AfficherOffreDisponibleAvecImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageResponse> HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.AfficherOffreDisponibleAvecImageAsync(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequest request) {
            return base.Channel.AfficherOffreDisponibleAvecImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageResponse> AfficherOffreDisponibleAvecImageAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequest inValue = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleAvecImageRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.dateArrive = dateArrive;
            inValue.Body.dateDepart = dateDepart;
            inValue.Body.nbPersonne = nbPersonne;
            return ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).AfficherOffreDisponibleAvecImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIResponse HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.AfficherOffreDisponibleGUI(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequest request) {
            return base.Channel.AfficherOffreDisponibleGUI(request);
        }
        
        public HotelWebService.ServiceDisponibilite2.Offre[] AfficherOffreDisponibleGUI(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequest inValue = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.dateArrive = dateArrive;
            inValue.Body.dateDepart = dateDepart;
            inValue.Body.nbPersonne = nbPersonne;
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIResponse retVal = ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).AfficherOffreDisponibleGUI(inValue);
            return retVal.Body.AfficherOffreDisponibleGUIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIResponse> HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.AfficherOffreDisponibleGUIAsync(HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequest request) {
            return base.Channel.AfficherOffreDisponibleGUIAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIResponse> AfficherOffreDisponibleGUIAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequest inValue = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.AfficherOffreDisponibleGUIRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.dateArrive = dateArrive;
            inValue.Body.dateDepart = dateDepart;
            inValue.Body.nbPersonne = nbPersonne;
            return ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).AfficherOffreDisponibleGUIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebService.ServiceDisponibilite2.getHotelResponse HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.getHotel(HotelWebService.ServiceDisponibilite2.getHotelRequest request) {
            return base.Channel.getHotel(request);
        }
        
        public HotelWebService.ServiceDisponibilite2.Hotel getHotel() {
            HotelWebService.ServiceDisponibilite2.getHotelRequest inValue = new HotelWebService.ServiceDisponibilite2.getHotelRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.getHotelRequestBody();
            HotelWebService.ServiceDisponibilite2.getHotelResponse retVal = ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).getHotel(inValue);
            return retVal.Body.getHotelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.getHotelResponse> HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.getHotelAsync(HotelWebService.ServiceDisponibilite2.getHotelRequest request) {
            return base.Channel.getHotelAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.getHotelResponse> getHotelAsync() {
            HotelWebService.ServiceDisponibilite2.getHotelRequest inValue = new HotelWebService.ServiceDisponibilite2.getHotelRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.getHotelRequestBody();
            return ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).getHotelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebService.ServiceDisponibilite2.faireReservationResponse HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.faireReservation(HotelWebService.ServiceDisponibilite2.faireReservationRequest request) {
            return base.Channel.faireReservation(request);
        }
        
        public HotelWebService.ServiceDisponibilite2.Reservation faireReservation(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            HotelWebService.ServiceDisponibilite2.faireReservationRequest inValue = new HotelWebService.ServiceDisponibilite2.faireReservationRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.faireReservationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idOffre = idOffre;
            inValue.Body.nomPersonne = nomPersonne;
            inValue.Body.prenom = prenom;
            inValue.Body.numeroCB = numeroCB;
            inValue.Body.nbPersonne = nbPersonne;
            HotelWebService.ServiceDisponibilite2.faireReservationResponse retVal = ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).faireReservation(inValue);
            return retVal.Body.faireReservationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.faireReservationResponse> HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap.faireReservationAsync(HotelWebService.ServiceDisponibilite2.faireReservationRequest request) {
            return base.Channel.faireReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite2.faireReservationResponse> faireReservationAsync(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            HotelWebService.ServiceDisponibilite2.faireReservationRequest inValue = new HotelWebService.ServiceDisponibilite2.faireReservationRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite2.faireReservationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idOffre = idOffre;
            inValue.Body.nomPersonne = nomPersonne;
            inValue.Body.prenom = prenom;
            inValue.Body.numeroCB = numeroCB;
            inValue.Body.nbPersonne = nbPersonne;
            return ((HotelWebService.ServiceDisponibilite2.HotelDisponibiliteSoap)(this)).faireReservationAsync(inValue);
        }
    }
}
