//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebService.ServiceReservation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomClientField;
        
        private System.DateTime dateArriveeField;
        
        private System.DateTime dateDepartField;
        
        private int numCarteBancaireField;
        
        private int nbPersonneField;
        
        private int dureeSejourField;
        
        private double prixTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nomClient {
            get {
                return this.nomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.nomClientField, value) != true)) {
                    this.nomClientField = value;
                    this.RaisePropertyChanged("nomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string prenomClient {
            get {
                return this.prenomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomClientField, value) != true)) {
                    this.prenomClientField = value;
                    this.RaisePropertyChanged("prenomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime dateArrivee {
            get {
                return this.dateArriveeField;
            }
            set {
                if ((this.dateArriveeField.Equals(value) != true)) {
                    this.dateArriveeField = value;
                    this.RaisePropertyChanged("dateArrivee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime dateDepart {
            get {
                return this.dateDepartField;
            }
            set {
                if ((this.dateDepartField.Equals(value) != true)) {
                    this.dateDepartField = value;
                    this.RaisePropertyChanged("dateDepart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int numCarteBancaire {
            get {
                return this.numCarteBancaireField;
            }
            set {
                if ((this.numCarteBancaireField.Equals(value) != true)) {
                    this.numCarteBancaireField = value;
                    this.RaisePropertyChanged("numCarteBancaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int nbPersonne {
            get {
                return this.nbPersonneField;
            }
            set {
                if ((this.nbPersonneField.Equals(value) != true)) {
                    this.nbPersonneField = value;
                    this.RaisePropertyChanged("nbPersonne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int dureeSejour {
            get {
                return this.dureeSejourField;
            }
            set {
                if ((this.dureeSejourField.Equals(value) != true)) {
                    this.dureeSejourField = value;
                    this.RaisePropertyChanged("dureeSejour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double prixTotal {
            get {
                return this.prixTotalField;
            }
            set {
                if ((this.prixTotalField.Equals(value) != true)) {
                    this.prixTotalField = value;
                    this.RaisePropertyChanged("prixTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReservation.ReservationHotelSoap")]
    public interface ReservationHotelSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faireReservation", ReplyAction="*")]
        HotelWebService.ServiceReservation.faireReservationResponse faireReservation(HotelWebService.ServiceReservation.faireReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faireReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebService.ServiceReservation.faireReservationResponse> faireReservationAsync(HotelWebService.ServiceReservation.faireReservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class faireReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="faireReservation", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceReservation.faireReservationRequestBody Body;
        
        public faireReservationRequest() {
        }
        
        public faireReservationRequest(HotelWebService.ServiceReservation.faireReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class faireReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idOffre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nomPersonne;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string prenom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int numeroCB;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int nbPersonne;
        
        public faireReservationRequestBody() {
        }
        
        public faireReservationRequestBody(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            this.login = login;
            this.password = password;
            this.idOffre = idOffre;
            this.nomPersonne = nomPersonne;
            this.prenom = prenom;
            this.numeroCB = numeroCB;
            this.nbPersonne = nbPersonne;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class faireReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="faireReservationResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceReservation.faireReservationResponseBody Body;
        
        public faireReservationResponse() {
        }
        
        public faireReservationResponse(HotelWebService.ServiceReservation.faireReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class faireReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HotelWebService.ServiceReservation.Reservation faireReservationResult;
        
        public faireReservationResponseBody() {
        }
        
        public faireReservationResponseBody(HotelWebService.ServiceReservation.Reservation faireReservationResult) {
            this.faireReservationResult = faireReservationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReservationHotelSoapChannel : HotelWebService.ServiceReservation.ReservationHotelSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationHotelSoapClient : System.ServiceModel.ClientBase<HotelWebService.ServiceReservation.ReservationHotelSoap>, HotelWebService.ServiceReservation.ReservationHotelSoap {
        
        public ReservationHotelSoapClient() {
        }
        
        public ReservationHotelSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationHotelSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationHotelSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationHotelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebService.ServiceReservation.faireReservationResponse HotelWebService.ServiceReservation.ReservationHotelSoap.faireReservation(HotelWebService.ServiceReservation.faireReservationRequest request) {
            return base.Channel.faireReservation(request);
        }
        
        public HotelWebService.ServiceReservation.Reservation faireReservation(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            HotelWebService.ServiceReservation.faireReservationRequest inValue = new HotelWebService.ServiceReservation.faireReservationRequest();
            inValue.Body = new HotelWebService.ServiceReservation.faireReservationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idOffre = idOffre;
            inValue.Body.nomPersonne = nomPersonne;
            inValue.Body.prenom = prenom;
            inValue.Body.numeroCB = numeroCB;
            inValue.Body.nbPersonne = nbPersonne;
            HotelWebService.ServiceReservation.faireReservationResponse retVal = ((HotelWebService.ServiceReservation.ReservationHotelSoap)(this)).faireReservation(inValue);
            return retVal.Body.faireReservationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebService.ServiceReservation.faireReservationResponse> HotelWebService.ServiceReservation.ReservationHotelSoap.faireReservationAsync(HotelWebService.ServiceReservation.faireReservationRequest request) {
            return base.Channel.faireReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebService.ServiceReservation.faireReservationResponse> faireReservationAsync(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            HotelWebService.ServiceReservation.faireReservationRequest inValue = new HotelWebService.ServiceReservation.faireReservationRequest();
            inValue.Body = new HotelWebService.ServiceReservation.faireReservationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idOffre = idOffre;
            inValue.Body.nomPersonne = nomPersonne;
            inValue.Body.prenom = prenom;
            inValue.Body.numeroCB = numeroCB;
            inValue.Body.nbPersonne = nbPersonne;
            return ((HotelWebService.ServiceReservation.ReservationHotelSoap)(this)).faireReservationAsync(inValue);
        }
    }
}
