//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebService.ServiceDisponibilite {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offre", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Offre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idOffreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelWebService.ServiceDisponibilite.TypeChambre numChambreField;
        
        private System.DateTime debField;
        
        private System.DateTime finField;
        
        private double prixTotalOffreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idOffre {
            get {
                return this.idOffreField;
            }
            set {
                if ((object.ReferenceEquals(this.idOffreField, value) != true)) {
                    this.idOffreField = value;
                    this.RaisePropertyChanged("idOffre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HotelWebService.ServiceDisponibilite.TypeChambre numChambre {
            get {
                return this.numChambreField;
            }
            set {
                if ((object.ReferenceEquals(this.numChambreField, value) != true)) {
                    this.numChambreField = value;
                    this.RaisePropertyChanged("numChambre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime deb {
            get {
                return this.debField;
            }
            set {
                if ((this.debField.Equals(value) != true)) {
                    this.debField = value;
                    this.RaisePropertyChanged("deb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime fin {
            get {
                return this.finField;
            }
            set {
                if ((this.finField.Equals(value) != true)) {
                    this.finField = value;
                    this.RaisePropertyChanged("fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double prixTotalOffre {
            get {
                return this.prixTotalOffreField;
            }
            set {
                if ((this.prixTotalOffreField.Equals(value) != true)) {
                    this.prixTotalOffreField = value;
                    this.RaisePropertyChanged("prixTotalOffre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeChambre", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TypeChambre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int numChambreField;
        
        private int nbLitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelWebService.ServiceDisponibilite.Reservation[] ListReservationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numChambre {
            get {
                return this.numChambreField;
            }
            set {
                if ((this.numChambreField.Equals(value) != true)) {
                    this.numChambreField = value;
                    this.RaisePropertyChanged("numChambre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int nbLits {
            get {
                return this.nbLitsField;
            }
            set {
                if ((this.nbLitsField.Equals(value) != true)) {
                    this.nbLitsField = value;
                    this.RaisePropertyChanged("nbLits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HotelWebService.ServiceDisponibilite.Reservation[] ListReservations {
            get {
                return this.ListReservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ListReservationsField, value) != true)) {
                    this.ListReservationsField = value;
                    this.RaisePropertyChanged("ListReservations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomClientField;
        
        private System.DateTime dateArriveeField;
        
        private System.DateTime dateDepartField;
        
        private int numCarteBancaireField;
        
        private int nbPersonneField;
        
        private int dureeSejourField;
        
        private double prixTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nomClient {
            get {
                return this.nomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.nomClientField, value) != true)) {
                    this.nomClientField = value;
                    this.RaisePropertyChanged("nomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string prenomClient {
            get {
                return this.prenomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomClientField, value) != true)) {
                    this.prenomClientField = value;
                    this.RaisePropertyChanged("prenomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime dateArrivee {
            get {
                return this.dateArriveeField;
            }
            set {
                if ((this.dateArriveeField.Equals(value) != true)) {
                    this.dateArriveeField = value;
                    this.RaisePropertyChanged("dateArrivee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime dateDepart {
            get {
                return this.dateDepartField;
            }
            set {
                if ((this.dateDepartField.Equals(value) != true)) {
                    this.dateDepartField = value;
                    this.RaisePropertyChanged("dateDepart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int numCarteBancaire {
            get {
                return this.numCarteBancaireField;
            }
            set {
                if ((this.numCarteBancaireField.Equals(value) != true)) {
                    this.numCarteBancaireField = value;
                    this.RaisePropertyChanged("numCarteBancaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int nbPersonne {
            get {
                return this.nbPersonneField;
            }
            set {
                if ((this.nbPersonneField.Equals(value) != true)) {
                    this.nbPersonneField = value;
                    this.RaisePropertyChanged("nbPersonne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int dureeSejour {
            get {
                return this.dureeSejourField;
            }
            set {
                if ((this.dureeSejourField.Equals(value) != true)) {
                    this.dureeSejourField = value;
                    this.RaisePropertyChanged("dureeSejour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double prixTotal {
            get {
                return this.prixTotalField;
            }
            set {
                if ((this.prixTotalField.Equals(value) != true)) {
                    this.prixTotalField = value;
                    this.RaisePropertyChanged("prixTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDisponibilite.HotelDisponibiliteSoap")]
    public interface HotelDisponibiliteSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfficherOffreDisponible", ReplyAction="*")]
        HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleResponse AfficherOffreDisponible(HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfficherOffreDisponible", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleResponse> AfficherOffreDisponibleAsync(HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faireReservation", ReplyAction="*")]
        HotelWebService.ServiceDisponibilite.faireReservationResponse faireReservation(HotelWebService.ServiceDisponibilite.faireReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/faireReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite.faireReservationResponse> faireReservationAsync(HotelWebService.ServiceDisponibilite.faireReservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AfficherOffreDisponibleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AfficherOffreDisponible", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequestBody Body;
        
        public AfficherOffreDisponibleRequest() {
        }
        
        public AfficherOffreDisponibleRequest(HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AfficherOffreDisponibleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dateArrive;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dateDepart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nbPersonne;
        
        public AfficherOffreDisponibleRequestBody() {
        }
        
        public AfficherOffreDisponibleRequestBody(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            this.login = login;
            this.password = password;
            this.dateArrive = dateArrive;
            this.dateDepart = dateDepart;
            this.nbPersonne = nbPersonne;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AfficherOffreDisponibleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AfficherOffreDisponibleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleResponseBody Body;
        
        public AfficherOffreDisponibleResponse() {
        }
        
        public AfficherOffreDisponibleResponse(HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AfficherOffreDisponibleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HotelWebService.ServiceDisponibilite.Offre[] AfficherOffreDisponibleResult;
        
        public AfficherOffreDisponibleResponseBody() {
        }
        
        public AfficherOffreDisponibleResponseBody(HotelWebService.ServiceDisponibilite.Offre[] AfficherOffreDisponibleResult) {
            this.AfficherOffreDisponibleResult = AfficherOffreDisponibleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class faireReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="faireReservation", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite.faireReservationRequestBody Body;
        
        public faireReservationRequest() {
        }
        
        public faireReservationRequest(HotelWebService.ServiceDisponibilite.faireReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class faireReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idOffre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nomPersonne;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string prenom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int numeroCB;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int nbPersonne;
        
        public faireReservationRequestBody() {
        }
        
        public faireReservationRequestBody(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            this.login = login;
            this.password = password;
            this.idOffre = idOffre;
            this.nomPersonne = nomPersonne;
            this.prenom = prenom;
            this.numeroCB = numeroCB;
            this.nbPersonne = nbPersonne;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class faireReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="faireReservationResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebService.ServiceDisponibilite.faireReservationResponseBody Body;
        
        public faireReservationResponse() {
        }
        
        public faireReservationResponse(HotelWebService.ServiceDisponibilite.faireReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class faireReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HotelWebService.ServiceDisponibilite.Reservation faireReservationResult;
        
        public faireReservationResponseBody() {
        }
        
        public faireReservationResponseBody(HotelWebService.ServiceDisponibilite.Reservation faireReservationResult) {
            this.faireReservationResult = faireReservationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelDisponibiliteSoapChannel : HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelDisponibiliteSoapClient : System.ServiceModel.ClientBase<HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap>, HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap {
        
        public HotelDisponibiliteSoapClient() {
        }
        
        public HotelDisponibiliteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelDisponibiliteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelDisponibiliteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelDisponibiliteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleResponse HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap.AfficherOffreDisponible(HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequest request) {
            return base.Channel.AfficherOffreDisponible(request);
        }
        
        public HotelWebService.ServiceDisponibilite.Offre[] AfficherOffreDisponible(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequest inValue = new HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.dateArrive = dateArrive;
            inValue.Body.dateDepart = dateDepart;
            inValue.Body.nbPersonne = nbPersonne;
            HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleResponse retVal = ((HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap)(this)).AfficherOffreDisponible(inValue);
            return retVal.Body.AfficherOffreDisponibleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleResponse> HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap.AfficherOffreDisponibleAsync(HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequest request) {
            return base.Channel.AfficherOffreDisponibleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleResponse> AfficherOffreDisponibleAsync(string login, string password, string dateArrive, string dateDepart, int nbPersonne) {
            HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequest inValue = new HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite.AfficherOffreDisponibleRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.dateArrive = dateArrive;
            inValue.Body.dateDepart = dateDepart;
            inValue.Body.nbPersonne = nbPersonne;
            return ((HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap)(this)).AfficherOffreDisponibleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebService.ServiceDisponibilite.faireReservationResponse HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap.faireReservation(HotelWebService.ServiceDisponibilite.faireReservationRequest request) {
            return base.Channel.faireReservation(request);
        }
        
        public HotelWebService.ServiceDisponibilite.Reservation faireReservation(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            HotelWebService.ServiceDisponibilite.faireReservationRequest inValue = new HotelWebService.ServiceDisponibilite.faireReservationRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite.faireReservationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idOffre = idOffre;
            inValue.Body.nomPersonne = nomPersonne;
            inValue.Body.prenom = prenom;
            inValue.Body.numeroCB = numeroCB;
            inValue.Body.nbPersonne = nbPersonne;
            HotelWebService.ServiceDisponibilite.faireReservationResponse retVal = ((HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap)(this)).faireReservation(inValue);
            return retVal.Body.faireReservationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite.faireReservationResponse> HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap.faireReservationAsync(HotelWebService.ServiceDisponibilite.faireReservationRequest request) {
            return base.Channel.faireReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebService.ServiceDisponibilite.faireReservationResponse> faireReservationAsync(string login, string password, string idOffre, string nomPersonne, string prenom, int numeroCB, int nbPersonne) {
            HotelWebService.ServiceDisponibilite.faireReservationRequest inValue = new HotelWebService.ServiceDisponibilite.faireReservationRequest();
            inValue.Body = new HotelWebService.ServiceDisponibilite.faireReservationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.idOffre = idOffre;
            inValue.Body.nomPersonne = nomPersonne;
            inValue.Body.prenom = prenom;
            inValue.Body.numeroCB = numeroCB;
            inValue.Body.nbPersonne = nbPersonne;
            return ((HotelWebService.ServiceDisponibilite.HotelDisponibiliteSoap)(this)).faireReservationAsync(inValue);
        }
    }
}
